In [10]:
import pandas as pd
from umap import UMAP
from sklearn.pipeline import make_pipeline 
from embetter.text import SentenceEncoder

In [11]:
model_name = 'all-MiniLM-L6-v2'
text_emb_pipeline = make_pipeline(
    SentenceEncoder(model_name),
    UMAP()
)

In [12]:
mm = pd.read_csv('../datasets/eliot_middlemarch.csv')
sentences = mm.sents.to_list()

In [13]:
X_tfm = text_emb_pipeline.fit_transform(sentences)

In [15]:
df = pd.DataFrame({"text":sentences, "chapter":mm.chapter})
df['x'] = X_tfm[:, 0]
df['y'] = X_tfm[:, 1]

In [19]:
df['sent_size'] = df['text'].apply(lambda x: len(x.split()))
df

,text,chapter,x,y,sent_size
0,Who that cares much to know the history of ma...,PRELUDE.,8.606354,2.299302,68
1,"Out they toddled from rugged Avila, wide-eyed ...",PRELUDE.,8.869586,2.465925,40
2,That child-pilgrimage was a fit beginning.,PRELUDE.,9.966560,2.205905,6
3,"Theresa’s passionate, ideal nature demanded an...",PRELUDE.,9.500031,2.133472,24
4,Her flame quickly burned up that light fuel; a...,PRELUDE.,9.750497,1.399239,36
...,...,...,...,...,...
11678,A new Theresa will hardly have the opportunity...,FINALE.,9.411123,2.280553,46
11679,But we insignificant people with our daily wor...,FINALE.,8.860480,-3.603154,35
11680,Her finely touched spirit had still its fine i...,FINALE.,10.462394,1.335819,15
11681,"Her full nature, like that river of which Cyru...",FINALE.,4.953501,1.311201,24
11682,But the effect of her being on those around he...,FINALE.,10.292094,1.138315,59

In [20]:
df.to_csv('mm_embedding.csv')

In [28]:
t = pd.read_csv('../datasets/kant_pure_reason.csv')

t

      Unnamed: 0                                                  0
0              0  Human reason, in one sphere of its cognition, ...
1              1  It falls into this difficulty without any faul...
2              2  It begins with principles, which cannot be dis...
3              3  With these principles it rises, in obedience t...
4              4  But it quickly discovers that, in this way, it...
...          ...                                                ...
5822        5822  78-79.    is their motto, under which they may...
5823        5823  As regards those who wish to pursue a scientif...
5824        5824  When I mention, in relation to the former, the...
5825        5825             The critical path alone is still open.
5826        5826  If my reader has been kind and patient enough ...

[5827 rows x 2 columns]

In [27]:
mm

,Unnamed: 0,org_index,chapter,sents
0,0,0,PRELUDE.,Who that cares much to know the history of ma...
1,1,0,PRELUDE.,"Out they toddled from rugged Avila, wide-eyed ..."
2,2,0,PRELUDE.,That child-pilgrimage was a fit beginning.
3,3,0,PRELUDE.,"Theresa’s passionate, ideal nature demanded an..."
4,4,0,PRELUDE.,Her flame quickly burned up that light fuel; a...
...,...,...,...,...
11678,11678,87,FINALE.,A new Theresa will hardly have the opportunity...
11679,11679,87,FINALE.,But we insignificant people with our daily wor...
11680,11680,87,FINALE.,Her finely touched spirit had still its fine i...
11681,11681,87,FINALE.,"Her full nature, like that river of which Cyru..."
11682,11682,87,FINALE.,But the effect of her being on those around he...

In [40]:
pd.read_csv('../../Downloads/embedding_data-2.csv')

,Unnamed: 0,text,sent_size,x,y,chapter
0,20,The pride of being ladies had something to do ...,63,8.104638,-1.659068,CHAPTER I.
1,24,Dorothea knew many passages of Pascal’s Pensee...,30,7.264685,-2.383707,CHAPTER I.
2,33,In Mr. Brooke the hereditary strain of Puritan...,56,7.891379,-1.968543,CHAPTER I.
3,34,She was regarded as an heiress; for not only h...,60,7.756501,-2.108856,CHAPTER I.
4,35,And how should Dorothea not marry?—a girl so h...,11,7.423277,-2.858918,CHAPTER I.
...,...,...,...,...,...,...
896,11668,"Such being the bent of Celia’s heart, it was i...",19,7.681426,-2.292696,FINALE.
897,11672,"Mr. Brooke lived to a good old age, and his es...",32,7.796404,-2.074696,FINALE.
898,11673,Sir James never ceased to regard Dorothea’s se...,61,7.453464,-2.565634,FINALE.
899,11674,Those who had not seen anything of Dorothea us...,26,7.254827,-2.811990,FINALE.
900,11679,But we insignificant people with our daily wor...,29,6.883538,-2.769789,FINALE.